# -*- coding: utf-8 -*-
"""TFL_Stations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QXpEPkND8N1OjkBHkAasp_ShMTishoid

# Exploring travel trends on the Transport for London network 🚉

Welcome to my analysis of the average monthly temperatures on Transport for London's (TfL) tube & train network!
This project aims to examine the patterns of travel on the Transport for London (TfL) network using [TfL open access data](http://crowding.data.tfl.gov.uk/) from 2007 to 2021.

We'll be taking a closer look at how commuter figures across the TfL network changes over the years and what factors may be behind these trends 📈. By examining these trends, we can get an idea of which areas are under-served and make further inferences.

With that said, let's get started!
"""

!pip install hvplot

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import geopandas as gpd
import folium
import hvplot
from shapely.geometry import Point
import plotly.graph_objs as go
from plotly.subplots import make_subplots
pd.set_option('display.max_rows', None)
# pd.set_option('display.max_columns', None)

pip install hvplot

"""## Preprocessing 🛠️

In this first section we will work on preprocessing. This involves cleaning ✨, transforming 🔀, and organizing 📂 our data to make it more suitable for analysis.

Don't worry, if you're not into that kind of stuff, no worries! You can collapse this section with a click of a button 🤏 and move on to the next. But if you stick around, you might learn some cool things!

So if you're ready for some data magic 🔮, feel free to expand this section and learn more about the specifics of preprocessing in my project!

### Loading TFL Station ridership data

#### Loading in 2007 to 2016 Entry / Exit data
"""

file_name='data/TFL Station Counts/Annual_Counts/multi-year-station-entry-and-exit-figures.xlsx'

sheet07='2007 Entry & Exit'
df2007=pd.read_excel(io=file_name, sheet_name=sheet07, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])
sheet08='2008 Entry & Exit'
df2008=pd.read_excel(io=file_name, sheet_name=sheet08, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet09='2009 Entry & Exit'
df2009=pd.read_excel(io=file_name, sheet_name=sheet09, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet10='2010 Entry & Exit'
df2010=pd.read_excel(io=file_name, sheet_name=sheet10, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet11='2011 Entry & Exit'
df2011=pd.read_excel(io=file_name, sheet_name=sheet11, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet12='2012 Entry & Exit'
df2012=pd.read_excel(io=file_name, sheet_name=sheet12, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet13='2013 Entry & Exit'
df2013=pd.read_excel(io=file_name, sheet_name=sheet13, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])
sheet14='2014 Entry & Exit'
df2014=pd.read_excel(io=file_name, sheet_name=sheet14, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])

sheet15='2015 Entry & Exit'
df2015=pd.read_excel(io=file_name, sheet_name=sheet15, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])
sheet16='2016 Entry & Exit'
df2016=pd.read_excel(io=file_name, sheet_name=sheet16, skiprows=6).drop(columns=[
                                                                        'Weekday',
                                                                        'Saturday',
                                                                        'Sunday',
                                                                        'Weekday.1',
                                                                        'Saturday.1',
                                                                        'Sunday.1'])
df2011.sample(5)

"""#### Loading in 2017 Entry / Exit data"""

# Loading in TFL Station Exit & Entry Spreadsheet for 2017
file_name =  '/content/AC2020_AnnualisedEntryExit.xlsx'
sheet =  'Annualised'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2017 = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2017=df2017.drop(columns=['entries',
                            'entries.1',
                            'entries.2',
                            'Unnamed: 7',
                            'exits',
                            'exits.1',
                            'exits.2',
                            'Unnamed: 11']).round()
df2017.sample(5)

# Loading in TFL Station Exit & Entry Spreadsheet for 2017
file_name =  '/content/AC2020_AnnualisedEntryExit.xlsx'
sheet =  'ByQhr'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2017hr = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2017hr=df2017hr.iloc[:,0:15]
df2017hr.sample(5)

"""#### Loading in 2018 Entry / Exit data

"""

#Loading in TFL Station Exit & Entry Spreadsheet for 2017
file_name =  'data/TFL Station Counts/Annual_Counts/AnnualisedEntryExit_2018.xlsx'
sheet =  'Annualised'
#Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2018 = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2018=df2018.drop(columns=['entries',
                            'entries.1',
                            'entries.2',
                            'entries.3',
                            'exits',
                            'exits.1',
                            'exits.2',
                            'exits.3']).round()
df2018.sample(5)

# Loading in TFL Station Exit & Entry Spreadsheet for 2018
file_name =  'data/TFL Station Counts/Hourly_Counts/ByQhrEntryExit_2018.xlsx'
sheet =  'ByQhr'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2018hr = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2018hr=df2018hr.iloc[:,0:15]
df2018hr.sample(5)

"""#### Loading in 2019 Entry / Exit data"""

# Loading in TFL Station Exit & Entry Spreadsheet for 2017
file_name =  'data/TFL Station Counts/Annual_Counts/AnnualisedEntryExit_2019.xlsx'
sheet =  'Annualised'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2019 = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2019=df2019.drop(columns=['entries',
                            'entries.1',
                            'entries.2',
                            'entries.3',
                            'exits',
                            'exits.1',
                            'exits.2',
                            'exits.3']).round()
df2019.sample(5)

# Loading in TFL Station Exit & Entry Spreadsheet for 2019
file_name =  'data/TFL Station Counts/Hourly_Counts/ByQhrEntryExit_2019.xlsx'
sheet =  'ByQhr'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2019hr = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2019hr=df2019hr.iloc[:,0:15]
df2019hr.sample(5)

"""#### Loading in 2020 Entry / Exit data"""

# Loading in TFL Station Exit & Entry Spreadsheet for 2020
file_name =  'data/TFL Station Counts/Annual_Counts/AC2020_AnnualisedEntryExit.xlsx'
sheet =  'Annualised'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2020 = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2020=df2020.drop(columns=['Entries',
                            'Entries.1',
                            'Entries.2',
                            'Entries.3',
                            'Exits',
                            'Exits.1',
                            'Exits.2',
                            'Exits.3']).round()
df2020.sample(5)

# Loading in TFL Station Exit & Entry Spreadsheet for 2020
file_name =  'data/TFL Station Counts/Hourly_Counts/AC2020_ByQhrEntryExit.xlsx'
sheet =  'ByQhr'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2020hr = pd.read_excel(io=file_name,
                         sheet_name=sheet,
                         skiprows=6).round()
convert_dict = {'Total': np.int32,
                'Early     ': np.int32,
                'AM Peak': np.int32,
                'Inter Peak': np.int32,
                'PM Peak': np.int32,
                'Evening   ': np.int32,
                'Late      ': np.int32}
df2020hr = df2020hr.astype(convert_dict)
df2020hr=df2020hr.iloc[:,0:15]
df2020hr.head(5)

"""#### Loading in 2021 Entry / Exit data"""

# Loading in TFL Station Exit & Entry Spreadsheet for 2021
file_name =  'data/TFL Station Counts/Annual_Counts/AC2021_AnnualisedEntryExit.xlsx'
sheet =  'Annualised'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2021 = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6)
df2021=df2021.drop(columns=['Entries',
                            'Entries.1',
                            'Entries.2',
                            'Entries.3',
                            'Exits',
                            'Exits.1',
                            'Exits.2',
                            'Exits.3']).round()
df2021.sample(5)

# Loading in TFL Station Exit & Entry Spreadsheet for 2021
file_name =  'data/TFL Station Counts/Hourly_Counts/AC2021_ByQhrEntryExit.xlsx'
sheet =  'ByQhr'
# Some Rows are skipped and irrelevant columns are dropped to standardize the DataFrame
df2021hr = pd.read_excel(io=file_name, sheet_name=sheet, skiprows=6).round()
convert_dict = {'Total': np.int32,
                'Early     ': np.int32,
                'AM Peak': np.int32,
                'Inter Peak': np.int32,
                'PM Peak': np.int32,
                'Evening   ': np.int32,
                'Late      ': np.int32}
df2021hr = df2021hr.astype(convert_dict)
df2021hr=df2021hr.iloc[:,0:15]
df2021hr.head(5)

"""###### In the Hourly DFs loaded in the categories are grouped into Early, AM Peak, Inter Peak,	PM Peak,	Evening, &	Late. These categories are specified as follows:
* 🌅 Early - 5:00 to 7:00
* ☀️ AM Peak - 7:00 to 10:00
* 🌞 Inter Peak - 10:00 to 16:00
* 🌇 PM Peak - 16:00 to 19:00
* 🌙 Evening - 19:00 to 22:00
* 🌃 Late - 22:00 to 05:00
"""

# The DataDrames contain the Stations and their associated TFL mode.
# Some stations contain multiple train modes however, so only 'unique' instances are called

print('2007', '-', '[LU]',
      df2007['Station'].nunique(),'stations')

print('2008', '-', '[LU]',
      df2008['Station'].nunique(),'stations') # East London Line decomissioned and joins London Overground

print('2009', '-', '[LU]',
      df2009['Station'].nunique(),'stations')

print('2010', '-', '[LU]',
      df2010['Station'].nunique(),'stations')

print('2011', '-', '[LU]',
      df2011['Station'].nunique(),'stations')

print('2012', '-', '[LU]',
      df2012['Station'].nunique(),'stations')

print('2013', '-', '[LU]',
      df2013['Station'].nunique(),'stations')

print('2014', '-', '[LU]',
      df2014['Station'].nunique(),'stations')

print('2015', '-', '[LU]',
      df2015['Station'].nunique(),'stations')

print('2016', '-', '[LU]',
      df2016['Station'].nunique(),'stations')

print('2017', '-',
      df2017['Mode'].unique(),
      df2017['Station'].nunique(),'stations') # Data provided in prior DFs is only for London Underground
print('2018', '-',
      df2018['Mode'].unique(),
      df2018['Station'].nunique(),'stations') # Stations opened on the TFLRail West route
print('2019', '-',
      df2019['Mode'].unique(),
      df2019['Station'].nunique(),'stations')
print('2020', '-',
      df2020['Mode'].unique(),
      df2020['Station'].nunique(),'stations') # More Stations opened on the TFLRail West route
                                              # TFLRail is rebranded as the Elizabeth Line(EZL) upon completion
print('2021', '-',
      df2021['Mode'].unique(),
      df2021['Station'].nunique(),'stations') # Nine Elms and Battersea Power Station added to the Northern Line

# Creating dfs with only London Underground data
df2017LU=df2017[df2017['Mode']=='LU']
df2018LU=df2018[df2018['Mode']=='LU']
df2019LU=df2019[df2019['Mode']=='LU']
df2020LU=df2020[df2020['Mode']=='LU']
df2021LU=df2021[df2021['Mode']=='LU']

pd.set_option('display.max_columns', None)

# For some reason, some of the column names have white space, as shown below.
print(df2017hr.keys())
print(df2018hr.keys())
print(df2019hr.keys())
print(df2020hr.keys())
print(df2021hr.keys())

# To correct this, the columns are stripped of whitespace
df2017hr.columns=df2017hr.keys().str.strip()
df2018hr.columns=df2018hr.keys().str.strip()
df2019hr.columns=df2019hr.keys().str.strip()
df2020hr.columns=df2020hr.keys().str.strip()
df2021hr.columns=df2021hr.keys().str.strip()
print(df2017hr.keys())
print(df2018hr.keys())
print(df2019hr.keys())
print(df2020hr.keys())
print(df2021hr.keys())

"""### Slicing the data by Days of the week

#### Slicing 2017 Entry / Exit data
"""

df2017hr=df2017hr.groupby(['year',
                           'NLC',
                           'day',
                           'Station',
                           'dir']).sum(numeric_only=True).reset_index()
df2017hr[df2017hr['day']=='MTF'].sum(numeric_only=True)[3:].sum()
print(df2017hr[df2017hr['day']=='MTF'].sum(numeric_only=True)[2:])

"""#### Slicing 2018 Entry / Exit data"""

df2018hr=df2018hr.groupby(['year',
                           'NLC',
                           'day',
                           'Station',
                           'dir']).sum(numeric_only=True).reset_index()
df2018hr[df2018hr['day']=='MTT'].sum(numeric_only=True)[3:].sum()
print(df2018hr[df2018hr['day']=='MTT'].sum(numeric_only=True)[2:])

"""#### Slicing 2019 Entry / Exit data"""

df2019hr=df2019hr.groupby(['year',
                           'NLC',
                           'day',
                           'Station',
                           'dir']).sum(numeric_only=True).reset_index()
df2019hr[df2019hr['day']=='MTT'].sum(numeric_only=True)[3:].sum()
print(df2019hr[df2019hr['day']=='MTT'].sum(numeric_only=True)[2:])

"""#### Slicing 2020 Entry / Exit data"""

df2020hr=df2020hr.groupby(['year',
                           'NLC',
                           'day',
                           'Station',
                           'dir']).sum(numeric_only=True).reset_index()
df2020hr[df2020hr['day']=='MTT'].sum(numeric_only=True)[3:].sum()
print(df2020hr[df2020hr['day']=='MTT'].sum(numeric_only=True)[2:])

"""#### Slicing 2021 Entry / Exit data"""

df2021hr=df2021hr.groupby(['year',
                           'NLC',
                           'day',
                           'Station',
                           'dir']).sum(numeric_only=True).reset_index()
df2021hr[df2021hr['day']=='MTT'].sum(numeric_only=True)[3:].sum()
print(df2021hr[df2021hr['day']=='MTT'].sum(numeric_only=True)[2:])

df2017hr.head()

dfs = [df2017hr, df2018hr, df2019hr, df2020hr, df2021hr]

# concatenating
df_mergedhr = pd.concat(dfs, axis=0, ignore_index=True)

# check the resulting data frame
df_mergedhr.sample(5)

"""### Grouping DFs and Standardizing formats

As the datasets have had their formats altered over the years, it is necessary for some formatting to ensure uniformity in our Dataframe.

The next cells will be doing just that to ensure we have just the data required for our analysis.
"""

df_grouped2007=df2007.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2007['million']=df_grouped2007['million']*1_000_000
df_grouped2007.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2007"}, inplace=True)
df_grouped2007.head(3)

df_grouped2008=df2008.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2008['million']=df_grouped2008['million']*1_000_000
df_grouped2008.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2008"}, inplace=True)
df_grouped2008.head(3)

df_grouped2009=df2009.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2009['million']=df_grouped2009['million']*1_000_000
df_grouped2009.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2009"}, inplace=True)
df_grouped2009.head(3)

df_grouped2010=df2010.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2010['million']=df_grouped2010['million']*1_000_000
df_grouped2010.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2010"}, inplace=True)
df_grouped2010.head(3)

df_grouped2011=df2011.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2011['million']=df_grouped2011['million']*1_000_000
df_grouped2011.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2011"}, inplace=True)
df_grouped2011.head(3)

df_grouped2012=df2012.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2012['million']=df_grouped2012['million']*1_000_000
df_grouped2012.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2012"}, inplace=True)
df_grouped2012.head(3)

df_grouped2013=df2013.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2013['million']=df_grouped2013['million']*1_000_000
df_grouped2013.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2013"}, inplace=True)
df_grouped2013.head(3)

df_grouped2014=df2014.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2014['million']=df_grouped2014['million']*1_000_000
df_grouped2014.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2014"}, inplace=True)
df_grouped2014.head(3)

df_grouped2015=df2015.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2015['million']=df_grouped2015['million']*1_000_000
df_grouped2015.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2015"}, inplace=True)
df_grouped2015.head(3)

df_grouped2016=df2016.groupby(['nlc', 'Station'], as_index=False).sum(numeric_only=True)
df_grouped2016['million']=df_grouped2016['million']*1_000_000
df_grouped2016.rename(columns={"nlc": "NLC",
                               "million": "En/Ex 2016"}, inplace=True)
df_grouped2016.head(3)

df_grouped2017LU=df2017LU.groupby(['NLC', 'Station'], as_index=False).sum('en/ex')
df_grouped2017LU.rename(columns={"en/ex": "En/Ex 2017"}, inplace=True)

df_grouped2017=df2017.groupby(['NLC', 'Station'], as_index=False).sum('en/ex')
df_grouped2017.rename(columns={"en/ex": "En/Ex 2017"}, inplace=True)
df_grouped2017.head(3)

df_grouped2018LU=df2018LU.groupby(['NLC', 'Station'], as_index=False).sum('en/ex')
df_grouped2018LU.rename(columns={"en/ex": "En/Ex 2018"}, inplace=True)

df_grouped2018=df2018.groupby(['NLC','Station'], as_index=False).sum('en/ex')
df_grouped2018.rename(columns={"en/ex": "En/Ex 2018"}, inplace=True)
df_grouped2018.head(3)

df_grouped2019LU=df2019LU.groupby(['NLC','Station'], as_index=False).sum('en/ex')
df_grouped2019LU.rename(columns={"en/ex": "En/Ex 2019"}, inplace=True)

df_grouped2019=df2019.groupby(['NLC','Station'], as_index=False).sum('en/ex')
df_grouped2019.rename(columns={"en/ex": "En/Ex 2019"}, inplace=True)
df_grouped2019.head(3)

df_grouped2020LU=df2020LU.groupby(['NLC','Station'], as_index=False).sum('En/Ex')
df_grouped2020LU.rename(columns={"En/Ex": "En/Ex 2020"}, inplace=True)

df_grouped2020=df2020.groupby(['NLC','Station'], as_index=False).sum('En/Ex')
df_grouped2020.rename(columns={"En/Ex": "En/Ex 2020"}, inplace=True)
df_grouped2020.head(3)

df_grouped2021LU=df2021LU.groupby(['NLC','Station'], as_index=False).sum('En/Ex')
df_grouped2021LU.rename(columns={"En/Ex": "En/Ex 2021"}, inplace=True)

df_grouped2021=df2021.groupby(['NLC','Station'], as_index=False).sum('En/Ex')
df_grouped2021.rename(columns={"En/Ex": "En/Ex 2021"}, inplace=True)
df_grouped2021.head(3)

"""Now that we have all our data formatted correctly, we can merge them all."""

# Merging all the Datasets prior to 2017
pt1 = pd.merge(
        pd.merge(
            pd.merge(
                pd.merge(
                    pd.merge(
                        pd.merge(
                            pd.merge(
                                pd.merge(
                                    pd.merge(df_grouped2007,
                                             df_grouped2008.drop(columns=['Station']),
                                             on='NLC',
                                             how='outer'),
                                    df_grouped2009.drop(columns=['Station']),
                                    on='NLC',
                                    how='outer'),
                                df_grouped2010.drop(columns=['Station']),
                                on='NLC',
                                how='outer'),
                            df_grouped2011.drop(columns=['Station']),
                            on='NLC',
                            how='outer'),
                        df_grouped2012,
                        on='NLC',
                        how='outer'),
                    df_grouped2013.drop(columns=['Station']),
                    on='NLC',
                    how='outer'),
                df_grouped2014.drop(columns=['Station']),
                on='NLC',
                how='outer'),
            df_grouped2015.drop(columns=['Station']),
            on='NLC',
            how='outer'),
        df_grouped2016.drop(columns=['Station']),
        on='NLC',
        how='outer')

# Merging all the Datasets post-2017.
pt2=pd.merge(
    pd.merge(
        pd.merge(
            pd.merge(df_grouped2017.drop(columns=['Station']),
                     df_grouped2018.drop(columns=['Station']),
                     on='NLC',
                     how='outer'),
            df_grouped2019.drop(columns=['Station']),
            on='NLC',
            how='outer'),
        df_grouped2020.drop(columns=['Station']),
        on='NLC',
        how='outer'),
    df_grouped2021, # NLC is dropped in all other DFs to avoid duplicate columns
    on='NLC',
    how='outer')

# Merging all the Datasets post-2017.
pt3=pd.merge(
    pd.merge(
        pd.merge(
            pd.merge(df_grouped2017LU.drop(columns=['Station']),
                     df_grouped2018LU.drop(columns=['Station']),
                     on='NLC',
                     how='outer'),
            df_grouped2019LU.drop(columns=['Station']),
            on='NLC',
            how='outer'),
        df_grouped2020LU.drop(columns=['Station']),
        on='NLC',
        how='outer'),
    df_grouped2021LU, # NLC is dropped in all other DFs to avoid duplicate columns
    on='NLC',
    how='outer')

# Merging the two merged DFs
df_merged=pd.merge(pt1,
                   pt2,
                   on='NLC',
                   how='outer')

# Merging the two merged DFs
df_mergedLU=pd.merge(pt1,
                     pt3,
                     on='NLC',
                     how='outer')

df_mergedLU

# We would like to have the NLC column at the front of the DF, we append it to the front using this
df_mergedLU = df_mergedLU[['Station_x'] + [x for x in df_mergedLU.columns if x != 'Station_x']]
df_mergedLU = df_mergedLU[['Station_y'] + [x for x in df_mergedLU.columns if x != 'Station_y']]
df_mergedLU = df_mergedLU[['Station'] + [x for x in df_mergedLU.columns if x != 'Station']]
df_mergedLU = df_mergedLU[['NLC'] + [x for x in df_mergedLU.columns if x != 'NLC']]
df_mergedLU.rename(columns={'Station_x': 'Station 2007',
                          'Station_y': 'Station 2012',
                          'Station': 'Station 2021'}, inplace=True, errors='raise')
df_mergedLU['Station 2007'] = df_mergedLU['Station 2007'].str.strip()
df_mergedLU['Station 2012'] = df_mergedLU['Station 2012'].str.strip()
df_mergedLU

# We would like to have the NLC column at the front of the DF, we append it to the front using this
df_merged = df_merged[['Station_x'] + [x for x in df_merged.columns if x != 'Station_x']]
df_merged = df_merged[['Station_y'] + [x for x in df_merged.columns if x != 'Station_y']]
df_merged = df_merged[['Station'] + [x for x in df_merged.columns if x != 'Station']]
df_merged = df_merged[['NLC'] + [x for x in df_merged.columns if x != 'NLC']]
df_merged.rename(columns={'Station_x': 'Station 2007',
                          'Station_y': 'Station 2012',
                          'Station': 'Station 2021'}, inplace=True, errors='raise')
df_merged['Station 2007']=df_merged['Station 2007'].str.strip()
df_merged['Station 2012']=df_merged['Station 2012'].str.strip()
df_merged.head(5)

"""In merging these datasets, we notice that many values are not present in the Station name columns. A few NaN values shown below are present in the 'Station 2021' column."""

df_mergedLU[df_mergedLU['Station 2012'].isnull()]

"""##### Notes:
As the East London Line was absorbed to the London Overground East section, the following amendments were made:
* *New Cross, New Cross Gate, Rotherhithe, Shadwell, Surrey Quays, and Wapping* station was closed from 2007 to 2010 and converted to the London Overground
* *Shoreditch* station was permanently closed after June 2006 and was later replaced by *Shoreditch High Street* station

These were all part of the [transfer of Silverlink's Metro lines to Transport for London](https://www.ealingtimes.co.uk/news/1782035.tfl-to-take-on-rail-network/) under the London Overground banner.
"""

df_merged.at[142,'Station 2021'] = 'New Cross'
df_merged.at[143,'Station 2021'] = 'New Cross Gate'
df_merged.at[178,'Station 2021'] = 'Rotherhithe'
df_merged.at[188,'Station 2021'] = 'Shadwell'
df_merged.at[190,'Station 2021'] = 'Shoreditch'
df_merged.at[211,'Station 2021'] = 'Surrey Quays'
df_merged.at[232,'Station 2021'] = 'Wapping'

df_mergedLU.at[142,'Station 2012'] = 'New Cross'
df_mergedLU.at[143,'Station 2012'] = 'New Cross Gate'
df_mergedLU.at[178,'Station 2012'] = 'Rotherhithe'
df_mergedLU.at[188,'Station 2012'] = 'Shadwell'
df_mergedLU.at[190,'Station 2012'] = 'Shoreditch'
df_mergedLU.at[211,'Station 2012'] = 'Surrey Quays'
df_mergedLU.at[232,'Station 2012'] = 'Wapping'
df_mergedLU.at[275,'Station 2012'] = 'Nine Elms'
df_mergedLU.at[276,'Station 2012'] = 'Battersea Power Station'

"""##### Note:
All these stations from the East London line were either permanently closed or underwent considerable reconstruction and became part of the London Overground under a new NLC.

For example, we can look at New Cross & New Cross Gate:
"""

# define value to search for
str_pattern = 'New Cross'

# row by row check for the string pattern in the row values
filt = (df_merged
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_merged.drop(columns=['Station 2007', 'Station 2012'])[filt]

"""We can now drop the other station name columns since we no longer need them."""

df_merged.drop(columns=['Station 2007', 'Station 2012'], inplace=True)
df_merged.rename(columns={"Station 2021": "Station"}, inplace=True)

df_mergedLU.drop(columns=['Station 2007', 'Station 2021'], inplace=True)
df_mergedLU.rename(columns={"Station 2012": "Station"}, inplace=True)

"""Finally, it would be helpful to know which lines go through these stations. To do this, we will load in a dataset containing all the TfL lines passing through each station and merge it."""

# Here is a dataframe with the line and network information of all Stations on the TfL network
df_lines = pd.read_csv('data/Geodata/Stations_20220221.csv').drop(columns=['EASTING','NORTHING','Zone','x','y'])
df_lines.sample(5)

# Now we can create a Dataframe with the station, its entry/exit data and its line and network information.
df_stationsLU=pd.merge(df_mergedLU,
                       df_lines,
                       on='NLC',
                       how='left' # Left merge since not all the stations in df_lines are in our df_merged dataset
                      ).drop(columns='NAME')
df_stationsLU.sample(5)

# Now we can create a Dataframe with the station, its entry/exit data and its line and network information.
df_stations=pd.merge(df_merged,
                     df_lines,
                     on='NLC',
                     how='left' # Left merge since not all the stations in df_lines are in our df_merged dataset
                    ).drop(columns='NAME')
df_stations.sample(5)

print(df_stations.shape)
df_stations.sample(5)

"""## Data analysis & visualization

Now our Dataframe is complete!
"""

df_stationsLU.to_csv("output/LU_stations.csv") # Saves our dataframe to the output folder
df_stationsLU.sample(5)

df_stations.to_csv("output/TfL_stations.csv") # Saves our dataframe to the output folder
df_stations.sample(5)

"""If you skipped the previous section, I have merged all the datasets into one dataframe containing all Entry & Exit data from 2007 to 2021. In this next section, we will use this data to analyse and visualise trends in travel on the TfL network.

But first, a little detour...

### A brief detour to discuss the Station NLC codes

As you may know, we have the issue of some TfL stations having the same or very similar names. Even more confusingly, some stations have different terminals within the same station classified under different NLC codes.

For the purpose of this analysis, we will treat stations with *different* NLC codes as being *distinct*. Below I have shown a couple stations which illustrate the point I am making.

**Canary Wharf, which has two¹ stations, in separate buildings under different NLC codes.**

¹ - The Canary Wharf EL station, shown in the map below is not present in the dataframe, as it only opened in May 2022.

![image](https://visitbytrain.info/maps/canarywharf.gif)
"""

# define value to search for
str_pattern = 'Canary Wharf'

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Bank and Monument are linked via underground interchange and are considered one station under one NLC code.**

![Bank and Monument Stations](https://substackcdn.com/image/fetch/w_1456,c_limit,f_webp,q_auto:good,fl_progressive:steep/https%3A%2F%2Fbucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com%2Fpublic%2Fimages%2F1e6c6e4c-305e-478e-9dea-903e650f5d80_400x457.png)
"""

# define value to search for
str_pattern = 'Bank and Monument'

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Euston, which has the Euston LU & Euston NR terminals, in the *same*  building under different NLC codes. Also, Euston Square, which is only a few minutes away.**"""

# define value to search for
str_pattern = 'Euston '

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Liverpool Street, which has the LU &  NR terminals, in the *same*  building under different NLC codes.**"""

# define value to search for
str_pattern = 'Liverpool '

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Heathrow, which has the LU &  NR terminals for its own individual airport terminals, in the *same*  building under different NLC codes**"""

# define value to search for
str_pattern = 'Heathrow'

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Paddington, which has the LU & NR terminals in the *same* building under different NLC codes**"""

# define value to search for
str_pattern = 'Paddington '

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""**Shepherd's Bush, which has the LU & NR terminals in the *same* building under different NLC codes**"""

# define value to search for
str_pattern = 'Shepherd'

# row by row check for the string pattern in the row values
filt = (df_stations
.apply(lambda r: r.astype('string').str.contains(str_pattern)
.any(), axis=1))

df_stations[filt]

"""##### Later, we could catergorize all stations which can reasonably be considered to be the same station as a single entity to get a broader idea of travel in London (for example, Euston NR & Euston LU).  
But for now, on to making cool graphs!

### Exploratory Data Analysis

Now that we have our Data ready, we can see how travel on the TfL is trending.
###### Note:
*It is worth noting that prior to 2017, the data **only** includes data for the London Underground (i.e The London Overground, DLR & Elizabeth Line are not accounted for)*

#### Annual Count data

*Presented below is the Transport for London Entry & Exit figures over the years*
"""

df_stationsLU.sort_values(by='En/Ex 2007', ascending=False, inplace=True)

df_stations[["En/Ex 2007",
             "En/Ex 2008",
             "En/Ex 2009",
             "En/Ex 2010",
             "En/Ex 2011",
             "En/Ex 2012",
             "En/Ex 2013",
             "En/Ex 2014",
             "En/Ex 2015",
             "En/Ex 2016", # Remember, the Datasets prior to 2017 ONLY contains London Underground data
             "En/Ex 2017",
             "En/Ex 2018",
             "En/Ex 2019",
             "En/Ex 2020",
             "En/Ex 2021"]].sum(axis=0).hvplot(kind='bar',
                                             title='Transport for London Entry & Exit figures over the years',
                                             xlabel='Period',
                                             frame_width=800,
                                             frame_height=400,
                                             ylabel='Figures (in Billions)',
                                             rot=45)
# Below is the number of Entries & Exits for 2007 to 2021.

"""***Presented below is the Transport for London Entry & Exit figures over the years***"""

import plotly.graph_objects as go

fig = go.Figure()

# Add traces for top 50 stations
for station in df_stationsLU['Station'].head(50):
    x = df_stationsLU.loc[df_stationsLU['Station'] == station, [f'En/Ex {year}' for year in range(2007, 2020)]].values[0]
    fig.add_trace(go.Scatter(x=list(range(2007, 2020)), y=x, mode='lines+markers', name=station))

# Set layout
fig.update_layout(
    title={
        'text': "Top 50 London Underground Stations by Entry/Exit (2007-2021)",
        'x': 0.5, # Center the title
        'y': 0.93, # Set the y position of the title
        'xanchor': 'center', # Center the title horizontally
        'yanchor': 'top' # Anchor the title to the top of the figure
    },
    xaxis_title='Year',
    yaxis_title='Entry/Exit',
    yaxis_type='log', # Set the y-axis scale to logarithmic
    height=1100,
    width=1000,
    plot_bgcolor='whitesmoke'
)

fig.show()

"""### Observations 🔎
Looking at the top 50 London Underground stations, we spot a few trends:
- Stratford station, having undergone major redevelopment in preparation for the 2012 Olympics, sky rockets from around 27M to 48M by 2011 - the same year Westfield Stratford City is completed. Further developments such as the opening  of the Elizabeth line have also put Stratford among the very busiest stations in London.
- A couple stations such as Charing Cross, and Tottenham Court Road have significant drops in passenger figures due to major redevelopment or renovation work being done at the stations during that period.

**Note:**
- There is a noticable decline from 2016 to 2017 in passenger count. The explanation seems to be because the method of estimation changes during that period, leading to some counts being slightly lower than before.

### Annual Count data *by period*

On a smaller scale, we can view the periodic breakdowns of Entry and Exit data.

**Presented below is the Transport for London Entry & Exit figures, by time period, over the years**

These graphs are further classified by Days of the week giving:
- Monday to Thursday
- Friday
- Saturday
- Sunday

***Reminder:***
    
The periodic categories are specified as follows:
* 🌅 Early - 5:00 to 7:00
* ☀️ AM Peak - 7:00 to 10:00
* 🌞 Inter Peak - 10:00 to 16:00
* 🌇 PM Peak - 16:00 to 19:00
* 🌙 Evening - 19:00 to 22:00
* 🌃 Late - 22:00 to 05:00

#### Monday to Thursday
"""

figure, axis = plt.subplots(3, 2, figsize=(16,10), sharey=True,  tight_layout=True)
labels=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late']
startangle=270
explode=(0.02, 0.02, 0.02, 0.02, 0.02, 0.02)
autopct='%1.2f%%'
fontsize=20

# Bar Chart Breakdown
# axis[1].bar(height=df2021hr[df2021hr['day']=='MTT'].sum(numeric_only=True)[3:].to_list(),
#             x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
# axis[1].set_title("Bar Chart Breakdown");
# axis[1].set_ylim(0, 3_500_000); # added line to set y limit

axis[0, 0].bar(height=df2017hr[df2017hr['day']=='MTF'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 0].set_title("2017", fontdict={'fontsize': fontsize});

axis[0, 1].bar(height=df2018hr[df2018hr['day']=='MTT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 1].set_title("2018", fontdict={'fontsize': fontsize});

axis[1, 0].bar(height=df2019hr[df2019hr['day']=='MTT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 0].set_title("2019", fontdict={'fontsize': fontsize});

axis[1, 1].bar(height=df2020hr[df2020hr['day']=='MTT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 1].set_title("2020", fontdict={'fontsize': fontsize});

axis[2, 0].bar(height=df2021hr[df2021hr['day']=='MTT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[2, 0].set_title("2021", fontdict={'fontsize': fontsize});

axis[0,0].set_ylim(0, 3_500_000)
axis[0,1].set_ylim(0, 3_500_000)
axis[1,0].set_ylim(0, 3_500_000)
axis[1,1].set_ylim(0, 3_500_000)
axis[2,0].set_ylim(0, 3_500_000)

figure.suptitle("Total Passenger Volume by Time Period (2017-2021)", fontsize=20)

figure.delaxes(axis[2,1])

"""**Friday**"""

figure, axis = plt.subplots(2, 2, figsize=(16,10), sharey=True,  tight_layout=True)
labels=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late']
startangle=270
explode=(0.02, 0.02, 0.02, 0.02, 0.02, 0.02)
autopct='%1.2f%%'
fontsize=20

axis[0, 0].bar(height=df2018hr[df2018hr['day']=='FRI'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 0].set_title("2018", fontdict={'fontsize': fontsize});

axis[0, 1].bar(height=df2019hr[df2019hr['day']=='FRI'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 1].set_title("2019", fontdict={'fontsize': fontsize});

axis[1, 0].bar(height=df2020hr[df2020hr['day']=='FRI'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 0].set_title("2020", fontdict={'fontsize': fontsize});

axis[1, 1].bar(height=df2021hr[df2021hr['day']=='FRI'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 1].set_title("2021", fontdict={'fontsize': fontsize});

axis[0,0].set_ylim(0, 3_500_000)
axis[0,1].set_ylim(0, 3_500_000)
axis[1,0].set_ylim(0, 3_500_000)
axis[1,1].set_ylim(0, 3_500_000)

# On the 2017 data, Friday is not classified separately and is included as 'MTF' unlike subsequent years

figure.suptitle("Total Passenger Volume by Time Period (2018-2021)", fontsize=20);

"""**Saturdays**"""

figure, axis = plt.subplots(3, 2, figsize=(16,10), sharey=True,  tight_layout=True)
labels=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late']
startangle=270
explode=(0.02, 0.02, 0.02, 0.02, 0.02, 0.02)
autopct='%1.2f%%'
fontsize=20

axis[0, 0].bar(height=df2017hr[df2017hr['day']=='SAT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 0].set_title("2017", fontdict={'fontsize': fontsize});

axis[0, 1].bar(height=df2018hr[df2018hr['day']=='SAT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 1].set_title("2018", fontdict={'fontsize': fontsize});

axis[1, 0].bar(height=df2019hr[df2019hr['day']=='SAT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 0].set_title("2019", fontdict={'fontsize': fontsize});

axis[1, 1].bar(height=df2020hr[df2020hr['day']=='SAT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 1].set_title("2020", fontdict={'fontsize': fontsize});

axis[2, 0].bar(height=df2021hr[df2021hr['day']=='SAT'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[2, 0].set_title("2021", fontdict={'fontsize': fontsize});

axis[0,0].set_ylim(0, 4_000_000)
axis[0,1].set_ylim(0, 4_000_000)
axis[1,0].set_ylim(0, 4_000_000)
axis[1,1].set_ylim(0, 4_000_000)
axis[2,0].set_ylim(0, 4_000_000)

figure.suptitle("Total Passenger Volume by Time Period (2017-2021)", fontsize=20);

figure.delaxes(axis[2,1])

"""**Sundays**"""

figure, axis = plt.subplots(3, 2, figsize=(16,10), sharey=True,  tight_layout=True)
labels=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late']
startangle=270
explode=(0.02, 0.02, 0.02, 0.02, 0.02, 0.02)
autopct='%1.2f%%'
fontsize=20

axis[0, 0].bar(height=df2017hr[df2017hr['day']=='SUN'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 0].set_title("2017", fontdict={'fontsize': fontsize});

axis[0, 1].bar(height=df2018hr[df2018hr['day']=='SUN'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[0, 1].set_title("2018", fontdict={'fontsize': fontsize});

axis[1, 0].bar(height=df2019hr[df2019hr['day']=='SUN'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 0].set_title("2019", fontdict={'fontsize': fontsize});

axis[1, 1].bar(height=df2020hr[df2020hr['day']=='SUN'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[1, 1].set_title("2020", fontdict={'fontsize': fontsize});

axis[2, 0].bar(height=df2021hr[df2021hr['day']=='SUN'].sum(numeric_only=True)[3:].to_list(),
               x=['Early', 'AM Peak', 'Inter Peak', 'PM Peak', 'Evening', 'Late'])
axis[2, 0].set_title("2021", fontdict={'fontsize': fontsize});

axis[0,0].set_ylim(0, 3_000_000)
axis[0,1].set_ylim(0, 3_000_000)
axis[1,0].set_ylim(0, 3_000_000)
axis[1,1].set_ylim(0, 3_000_000)
axis[2,0].set_ylim(0, 3_000_000)

figure.suptitle("Total Passenger Volume by Time Period (2017-2021)", fontsize=20);

figure.delaxes(axis[2,1])

"""**Presented below is the Entry/Exit figures by time period, as percenatges, over the years**"""

x = ('2017', '2018', '2019', '2020', '2021');

periods = {
    'Early': np.array([410606, 426922, 422622, 217860, 301384]),
    'AM Peak': np.array([3050039, 3049475, 3100335, 779180, 1744411]),
    'Inter Peak': np.array([2880265, 2920222, 2971552, 829986, 1979360]),
    'PM Peak': np.array([3183198, 3194781, 3254342, 834653, 2011992]),
    'Evening': np.array([1439332, 1430876, 1447731, 266806, 893644]),
    'Late': np.array([637978, 580478, 581302, 71054, 419004])
};

total = np.sum(list(periods.values()), axis=0);
bottom = np.zeros(len(x));

width = 0.5

fig, ax = plt.subplots();

for boolean, periods in periods.items():
    p = ax.bar(x, periods / total * 100, width, label=boolean, bottom=bottom);
    bottom += periods / total * 100
    for i, bar in enumerate(p):
        x_pos = bar.get_x() + bar.get_width() / 2
        y_pos = bar.get_y() + bar.get_height() / 2
        value = '{:.1f}%'.format(periods[i] / total[i] * 100);
        ax.text(x_pos, y_pos, value, ha='center', va='center');

ax.set_title("Percentage of passengers during different periods");

# Move the legend outside the axis
ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.1), ncol=6);

plt.show();

"""###### Observations 🔎

- 🦠 Unsurprisingly, the Covid-19 pandemic has had a significant impact on TfL's passenger numbers in 2020 and 2021.

- 📉 The fraction of passengers travelling during the 'AM Peak' period has dropped from an average of 26.3% to 23.7% in 2021. 💼 This could be due to the [rise of hybrid/remote work schedules](https://www.ons.gov.uk/employmentandlabourmarket/peopleinwork/employmentandemployeetypes/articles/ishybridworkingheretostay/2022-05-23), as more people are able to work from home and avoid the rush hour commute. The other periods have remained relatively stable over the years.

It will be interesting to see how these trends develop in 2022 when more data is made available.

### Creating indexes

Indexes can also be applied to gain insights into passenger behavior and usage patterns. By creating an index based on factors such as station popularity, time of day, and day of the week, we can identify the busiest and least busy stations, as well as how other stations on the network are trending.

As we noticed earlier, the Covid-19 pandemic has had a drastic effect on commuter figures through London. To find the impact of the pandemic on ridership at specific stations, the average passengers for pre and post-covid years is calculated and used to create the 'Post-Covid impact' index (PCI). The calculated index will be a factor between 0 & 1 representing how close the ridership is to pre-COVID levels. That is to say:
- *The closer a station's 'Post-Covid impact' index is to 1, the less affected it was because its commuter figure is closer to pre-pandemic levels.*
- *and the closer a station's index is to 0, the more affected it was as its commuter figure is significantly lower than pre-pandemic levels.*

It is worth noting that some specific change in passenger behavior in this period is not attributable to the effects of COVID. For example, changes in passenger behaviour (adoption of hybrid/remote work schedules), station closure or network changes can also impact the data. We will look into this later on and comment on any areas where this is likely the case.

**Note:**
All stations which opened after 2019 or were closed for a large portion of this period (Heathrow Terminal 4), will not be considered in this analysis.
"""

df_stations['Post-Covid impact'] = 1-(df_stations[["En/Ex 2017", "En/Ex 2018", "En/Ex 2019"]].mean(axis=1, skipna=True) -
                                    df_stations[["En/Ex 2021"]].mean(axis=1, skipna=False))/(
                                    df_stations[["En/Ex 2017", "En/Ex 2018", "En/Ex 2019"]].mean(axis=1, skipna=True))
df_stations.sort_values('Post-Covid impact', ascending=True, inplace=True)
df_stations=df_stations[df_stations['Post-Covid impact'] > 0]
df_stations.head(5)

df1 = pd.read_csv('data/Geodata/Stations_20220221.csv')
df1 = df1.drop(df1[df1.LINES == 'Tramlink'].index) # Dropping any stations on the Tramlink Network
df1.sample(1)

"""**Plotted below are the most affected stations by our 'Post-Covid impact' index**"""

px.bar(df_stations[df_stations['Post-Covid impact'] > 0]
       # Drops stations with NaN or 0 values (Station was closed)
       .head(20),
       y='Station',
       x='Post-Covid impact',
       title='Bottom 20 Stations by PCI',
       height=750
      )

"""**Plotted below are the least affected stations by our 'Post-Covid impact' index**"""

px.bar(df_stations[df_stations['Post-Covid impact'] > 0]
       # Drops stations with NaN or 0 values (Station was closed)
       .tail(20),
       y='Station',
       x='Post-Covid impact',
       title='Top 20 Stations by PCI',
       height=750
      )

# The figures may add up to more than 30 as a station can be on multiple TfL networks

print('Out of the top 30 stations by PCI:')
print('-', df_stations.tail(30)[df_stations.tail(30)['London Underground'] == 'Yes'].shape[0], 'are on the London Underground')
print('-', df_stations.tail(30)[df_stations.tail(30)['London Overground'] == 'Yes'].shape[0], 'are on the London Overground')
print('-', df_stations.tail(30)[df_stations.tail(30)['DLR'] == 'Yes'].shape[0], 'are on the DLR')
print('-', df_stations.tail(30)[df_stations.tail(30)['Elizabeth Line'] == 'Yes'].shape[0], 'are on the Elizabeth Line')
print(" ")
print('Out of the bottom 30 stations by PCI:')
print('-', df_stations.head(30)[df_stations.head(30)['London Underground'] == 'Yes'].shape[0], 'are on the London Underground')
print('-', df_stations.head(30)[df_stations.head(30)['London Overground'] == 'Yes'].shape[0], 'are on the London Overground')
print('-', df_stations.head(30)[df_stations.head(30)['DLR'] == 'Yes'].shape[0], 'are on the DLR')
print('-', df_stations.head(30)[df_stations.head(30)['Elizabeth Line'] == 'Yes'].shape[0], 'are on the Elizabeth Line')

"""As we can see the stations most affected are largely London Underground stations.
Also, a lot of the newly opened Elizabeth line stations score very highly on PCI indicating little or no effect post-pandemic

Another interesting angle is looking at how the network has changed in the past few years.

As I mentioned earlier, not all recent change is attributable to the effects of the pandemic. For a snapshot of this, we will create two indices 'Upturn' and 'Downturn'. These indexes will look at the stations with the greatest upturn and downturn in commuter figures after 2020 respectively.
"""

df_downturn=pd.merge(df_merged[df_merged['En/Ex 2020'] > df_merged['En/Ex 2021']],
                     df1,
                     on='NLC') # Creating a DF of all the stations which saw a decrease in commuter figures
df_downturn.drop([32], inplace=True) # Dropping East Acton Station
df_downturn['Downturn'] = df_downturn["En/Ex 2021"]/df_downturn["En/Ex 2020"] # Calculating the 'Downturn' of the selected stations
df_downturn = df_downturn[['Downturn'] + [x for x in df_downturn.columns if x != 'Downturn']] # Just rearrnging the order of the columns to place Downturn first
df_downturn = df_downturn.query('Downturn <= 0.75') # Setting the qualifier for stations in the DF
df_downturn.sort_values('Downturn', ascending=True, inplace=True)
df_downturn['Downturn']=df_downturn['Downturn'].round(3)
df_downturn = df_downturn.head(30)
df_downturn["Coordinates"] = list(zip(df_downturn.EASTING, df_downturn.NORTHING)) # Creating geodata
df_downturn["Coordinates"] = df_downturn["Coordinates"].apply(Point)
gdf_downturn = gpd.GeoDataFrame(df_downturn, geometry="Coordinates") # Creates a Geopandas DF with the geodata
df_downturn.shape[0] # Shows how many stations are present in the DF.

"""**Notes:**
- East Acton station [underwent extensive renovation from 2021 to 2022](https://web.archive.org/web/20230130222836/https://tfl.gov.uk/corporate/transparency/freedom-of-information/foi-request-detail?referenceId=FOI-2730-2122) and was closed during this period. As such, it will be dropped as its data is incomplete.

"""

px.bar(df_downturn.sort_values('Downturn', ascending=True),
       # Threshold of 7 non-NA values to filter stations with less than 4 years of data
       y='Station',
       x='Downturn',
       height=850,
       title='TfL Stations by Downturn',
       range_x=[0, 1]
)

df_upturn=pd.merge(df_merged[df_merged['En/Ex 2020'] < df_merged['En/Ex 2021']],
                   df1,
                   on='NLC') # Creating a DF of all the stations which saw an increase in commuter figures
df_upturn['Upturn'] = df_upturn["En/Ex 2021"]/df_upturn["En/Ex 2020"] # Calculating the 'Upturn' of the selected stations
df_upturn = df_upturn[['Upturn'] + [x for x in df_upturn.columns if x != 'Upturn']] # Just rearrnging the order of the columns to place Downturn first
df_upturn = df_upturn.query('Upturn >= 1.7') # Setting the qualifier for stations in the DF
df_upturn.sort_values('Upturn', ascending=False, inplace=True)
df_upturn['Upturn']=df_upturn['Upturn'].round(3)
df_upturn = df_upturn.head(30)
df_upturn["Coordinates"] = list(zip(df_upturn.EASTING, df_upturn.NORTHING)) # Creating geodata
df_upturn["Coordinates"] = df_upturn["Coordinates"].apply(Point)
gdf_upturn = gpd.GeoDataFrame(df_upturn, geometry="Coordinates") # Creates a Geopandas DF with the geodata
df_upturn.shape[0] # Shows how many stations are present in the DF.

df_upturn.head(5)

px.bar(df_upturn.sort_values('Upturn', ascending=True),
       y='Station',
       x='Upturn',
       height=850,
       title='TfL stations by Upturn',
       log_x=True
       # I made this a log graph to since Twyford's PCI was so high
)

"""**Below we can see the breakdown of which networks carry these stations**"""

print('Out of the top 30 stations by Downturn:')
print('-', gdf_downturn[gdf_downturn['London Underground'] == 'Yes'].shape[0], 'are on the London Underground')
print('-', gdf_downturn[gdf_downturn['London Overground'] == 'Yes'].shape[0], 'are on the London Overground')
print('-', gdf_downturn[gdf_downturn['DLR'] == 'Yes'].shape[0], 'are on the DLR')
print('-', gdf_downturn[gdf_downturn['Elizabeth Line'] == 'Yes'].shape[0], 'is on the Elizabeth Line')
print(" ")
print('Out of the top 30 stations by Upturn:')
print('-', gdf_upturn[gdf_upturn['London Underground'] == 'Yes'].shape[0], 'are on the London Underground')
print('-', gdf_upturn[gdf_upturn['London Overground'] == 'Yes'].shape[0], 'are on the London Overground')
print('-', gdf_upturn[gdf_upturn['DLR'] == 'Yes'].shape[0], 'are on the DLR')
print('-', gdf_upturn[gdf_upturn['Elizabeth Line'] == 'Yes'].shape[0], 'are on the Elizabeth Line')

# The figures may add up to more than 30 as a station can be on multiple TfL networks

"""###### Observations 🔎
- 📉 We notice that 28 of the 30 stations trending downward are on the London Underground.
- 📈 7 of the stations on the newly built Elizabeth line also flesh out the stations trending upward.

### Plotting Stations

In this next segment, we will be creating indexes and plotting the TfL stations to analyze the commuter data.

#### A couple things we'll need to make our maps look better...

These are a couple utlities and calls that will make our graphs down below look better and more informative. Again, you can choose to collapse this section with a click of a button 🤏 and move on to the next. That is where all the fun is anyway.
"""

tube_lines = {
    "Bakerloo":             {"id":"B", "colour":"#B36305", "network":"Tube"},
    "Central":              {"id":"C", "colour":"#E32017", "network":"Tube"},
    "Circle":               {"id":"I", "colour":"#FFD300", "network":"Tube"},
    "Elizabeth line":       {"id":"X", "colour":"#7156A5", "network":"Rail"},
    "DLR":                  {"id":"L", "colour":"#00A4A7", "network":"Rail"},
    "District":             {"id":"D", "colour":"#00782A", "network":"Tube"},
    "Hammersmith & City":   {"id":"H", "colour":"#F3A9BB", "network":"Tube"},
    "Jubilee":              {"id":"J", "colour":"#A0A5A9", "network":"Tube"},
    "Metropolitan":         {"id":"M", "colour":"#9B0056", "network":"Tube"},
    "Northern":             {"id":"N", "colour":"#000000", "network":"Tube"},
    "London Overground":    {"id":"O", "colour":"#EE7C0E", "network":"Rail"},
    "Piccadilly":           {"id":"P", "colour":"#003688", "network":"Tube"},
    "Tramlink":             {"id":"T", "colour":"#84B817", "network":"Tramlink"},
    "Victoria":             {"id":"V", "colour":"#0098D4", "network":"Tube"},
    "Waterloo & City":      {"id":"W", "colour":"#95CDBA", "network":"Tube"}
} # The Tube lines and their corresponding colour scheme and network.

# Define the style function for
def style_function(feature):
    line_id = feature["properties"]["id"]
    line_colour = tube_lines[line_id]["colour"]
    return {
        "color": line_colour,
        "weight": 4,
        "opacity": 0.8,
    }

ldn_df = gpd.read_file("data/Geodata/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")
ldn_df.sample(3)

df1 = pd.read_csv('data/Geodata/Stations_20220221.csv')
df1 = df1.drop(df1[df1.LINES == 'Tramlink'].index)
df1.drop(columns=['NETWORK',
                  'LINES',
                  'London Underground',
                  'Elizabeth Line',
                  'London Overground',
                  'DLR'], inplace=True)
df1.sample(4)

df1["Coordinates"] = list(zip(df1.EASTING, df1.NORTHING))
df1["Coordinates"] = df1["Coordinates"].apply(Point)
gdf = gpd.GeoDataFrame(df1, geometry="Coordinates")
gdf.sample()

gdf_night=gdf[gdf['Night Tube?']=='Yes']

url = (
    "https://raw.githubusercontent.com/Osakwe1/vis/master/tubecreature/data"
)
tfl_network = f"{url}/tfl_lines.json"
london_ug = f"{url}/lu_lines.geojson"
nighttube = f"{url}/night_tube.geojson"

"""Now, we'll set a threshold for which station will make it on our maps and explain any reasons for disqualification"""

df_plot=df_stations[df_stations['Post-Covid impact'] > 0].sort_values('Post-Covid impact', ascending=False)
df_plot['Post-Covid impact']=df_plot['Post-Covid impact'].round(3)
print(df_plot.shape)
df_plot.head()

"""##### Done!

Now that we have all this set up, we can begin creating plots of our data.

#### Plots using Folium, Geopandas & Matplotlib

##### As a start, here is every station on the TfL network (including Tramlink!)
"""

### Creating a Geopandas dataframe of all TfL stations
df_all=pd.merge(df_plot,
                df1,
                on='NLC',
                how='inner').drop(columns=['NETWORK', 'Zone'])
df_all["Coordinates"] = list(zip(df_all.EASTING, df_all.NORTHING))
df_all["Coordinates"] = df_all["Coordinates"].apply(Point)
gdf_all = gpd.GeoDataFrame(df_all, geometry="Coordinates")

# Creating a Geopandas dataframe of the bottom 30 stations by the 'Post-Covid impact' index
df_btm30=pd.merge(df_plot.tail(30),
                  df1,
                  on='NLC',
                  how='inner')
df_btm30["Coordinates"] = list(zip(df_btm30.EASTING, df_btm30.NORTHING))
df_btm30["Coordinates"] = df_btm30["Coordinates"].apply(Point)
gdf_btm30 = gpd.GeoDataFrame(df_btm30, geometry="Coordinates")

# Creating a Geopandas dataframe of the top 30 stations by the 'Post-Covid impact' index
df_top30=pd.merge(df_plot.head(30),
                  df1,
                  on='NLC',
                  how='inner').drop(columns=['NETWORK'])
df_top30["Coordinates"] = list(zip(df_top30.EASTING, df_top30.NORTHING))
df_top30["Coordinates"] = df_top30["Coordinates"].apply(Point)
gdf_top30 = gpd.GeoDataFrame(df_top30, geometry="Coordinates")

# A plot of the all TfL stations
fig, gax = plt.subplots(figsize=(18, 18))

ldn_df.plot(ax=gax, edgecolor="black", color="white")
gdf_all.plot(ax=gax, color='green', alpha = 0.5)

"""**This is a nice map but it doesnt really show us where the stations are or which lines are running through them.**

 To produce a more informative map, we can use Folium! Here is a map of all the TfL lines running through London plotted using Folium:
"""

# Create the GeoJson layer with the style function
map = folium.Map(location=[51.55, -0.33], tiles="Stamen Terrain", zoom_start=9)

tfl_layer = folium.GeoJson(
    tfl_network,
    name="Tfl map",
    style_function=style_function
)
tube_layer = folium.GeoJson(
    london_ug,
    name="Tube map",
    style_function=style_function
)
# Add the layer to the map
tfl_layer.add_to(map)
# nighttube.add_to(map)

# Create a legend using the tube_lines dictionary
legend_html = """
<div style="position: fixed;
     bottom: 50px;
     left: 50px;
     width: 160px;
     height: 500px;
     border: 2px solid grey; z-index:9999; font-size:14px;
     background-color:white;
     ">
     &nbsp; TfL Lines <br>
"""

for line_name, line_info in tube_lines.items():
    legend_html += f"""
     &nbsp; <span style="color:{line_info['colour']};
                  font-size: 20px;">&#9679;</span>
                  {line_name} <br>
    """

legend_html += "</div>"

map.get_root().html.add_child(folium.Element(legend_html))

map

"""##### Now, here is the map containing all TfL stations using Folium and json:"""

map = folium.Map(location=[51.55, -0.33], tiles="Stamen Terrain", zoom_start=9)
# folium.GeoJson(data=ldn_df["geometry"]).add_to(map)

for i,row in gdf.iterrows():
    #Setup the content of the popup
    iframe = folium.IFrame(str(row["NAME"] + ' St.'))

    #Initialise the popup using the iframe
    popup = folium.Popup(iframe, min_width= 100, max_width=200)
    #Add each row to the map
    folium.Marker(location=[row['y'],row['x']],
                  popup = popup).add_to(map)

folium.GeoJson(tfl_network, name="Tube map", style_function=style_function).add_to(map)

folium.LayerControl().add_to(map)

# Create a legend using the tube_lines dictionary
legend_html = """
<div style="position: fixed;
     bottom: 50px;
     left: 50px;
     width: 160px;
     height: 480px;
     border: 2px solid grey;
     z-index:9999;
     font-size:14px;
     background-color:white;
     ">
     &nbsp; TfL Lines <br>
"""

for line_name, line_info in tube_lines.items():
    legend_html += f"""
     &nbsp; <span style="color:{line_info['colour']};
                  font-size: 20px;">&#9679;</span>
                  {line_name} <br>
    """

legend_html += "</div>"

map.get_root().html.add_child(folium.Element(legend_html))

map

"""So now we know how the plots look, let's build some maps

Earlier, we created the 'Post-covid index' to take a deeper look at recent trends on the TfL network. Now for an even clearer image, we will be plotting the stations in both DFs.

###### Here we have the top 30 & bottom 30 stations by 'Post-covid index' in blue and red.
"""

fig, gax = plt.subplots(figsize=(18, 18))
ldn_df.plot(ax=gax, edgecolor="black", color="ghostwhite");
gdf_btm30.plot(ax=gax, color='red', alpha = 0.5) # Plotting of the bottom 30 stations by 'Post-Covid impact'
gdf_top30.plot(ax=gax, color='blue', alpha = 0.5) # Plotting of the top 30 stations by 'Post-Covid impact'

# Setting up the link to a Tfl route map I modified to show the individual lines
url = (
    "https://raw.githubusercontent.com/Osakwe1/vis/master/tubecreature/data"
)
tfl_network = f"{url}/tfl_lines.json"
style1 = {'fillColor': '#228B22', 'lineColor': '#228B22'}
style2 = {'fillColor': '#00FFFFFF', 'lineColor': '#00FFFFFF'}
# Setting up map to focus in on London
map = folium.Map(location=[51.55, -0.2], tiles="Stamen Terrain", zoom_start=10)

for i,row in gdf_top30.iterrows():
    # Setup the contents of the popup
    iframe = folium.IFrame(f'{str(row["NAME"])} \n Zone: {str(row["Zone"])} \n Lines: {str(row["LINES"])} \n PCI: {str(row["Post-Covid impact"])}',
                           width='100px',
                           height='150px')

    # Initialise the popup using the iframe
    popup = folium.Popup(iframe)

    # Add each station to the map
    folium.Marker(location=[row['y'],row['x']],
                  popup = popup, icon=folium.Icon(color='lightblue', icon='')).add_to(map)

for i,row in gdf_btm30.iterrows():
    # Setup the contents of the popup
    iframe = folium.IFrame(f'{str(row["NAME"])} Station \n Zone: {str(row["Zone"])} \n Lines: {str(row["LINES"])} \n PCI: {str(row["Post-Covid impact"])}',
                          width='100px',
                          height='150px')

    # Initialise the popup using the iframe
    popup = folium.Popup(iframe)

    # Add each station to the map
    folium.Marker(location=[row['y'],row['x']],
                  popup = popup, icon=folium.Icon(color='red', icon='')).add_to(map)

# Initialise the tfl route map
folium.GeoJson(tfl_network, name="Tube map", style_function=style_function).add_to(map)
# folium.GeoJson(data=ldn_df2["geometry"], name="Inner/Outer London map").add_to(map)

# Create a legend using the tube_lines dictionary
legend_html = """
<div style="position: fixed;
     bottom: 50px;
     left: 50px;
     width: 160px;
     height: 480px;
     border: 2px solid grey;
     z-index:9999;
     font-size:14px;
     background-color:white;
     ">
     &nbsp; TfL Lines <br>
"""

for line_name, line_info in tube_lines.items():
    legend_html += f"""
     &nbsp; <span style="color:{line_info['colour']};
                  font-size: 20px;">&#9679;</span>
                  {line_name} <br>
    """

legend_html += "</div>"

map.get_root().html.add_child(folium.Element(legend_html))

folium.LayerControl().add_to(map)

map

"""### Observations 🔎

Looking at the bottom 30 stations by Post-Covid Index, we spot a few trends:
- 21 of the 30 stations selected (70%) are within the Zone 1 fare
- Airport terminals Heathrow 2&3 EL, & London City Airport are included in the bottom 30.

For comparison, looking at the top 30 stations by Post-Covid Index:
- Only 1 of the 30 stations selected are within the Zone 1 fare zone, the Paddington NR station which has the newly finished Elizabeth line.

Also, there is an oddity that I find difficult to explain:
- Poplar and West India Quay stations are only a few metres apart (as displayed below). Poplar usually ranks among the busiest DLR stations however Poplar ranks ***last*** among all TfL stations by PCI while West India Quay ranks in the top 30. The likely explanation would be a closure of the station but there are seemingly no reports to support this possibility.
Other unlikely explanations were:
    *  West India Quay is near to the Canary Wharf EL station but that station only opened in May 2022 and both Poplar and West India Quay are Out-of-Station Interchanges (OSIs) for the Canary Wharf EL station.
    *  Workers commuting to the Canary Wharf may choose to go to the West India Quay station but the weekday entry and exit figures for the two stations are similar and there is no other reason to suggest chanegs in commuter behaviour.
  
**Note:**
I had filed a FOI request to information about this [issue](https://tfl.gov.uk/corporate/transparency/freedom-of-information/foi-request-detail?referenceId=FOI-3327-2223) but was declined as 'locating, retrieving and extracting data from other information would exceed the appropriate limit.'

![image.png](attachment:image.png)

Earlier, we created the upturn and downturn indexes to take a deeper look at recent trends on the TfL network. Now for an even clearer image, we will be plotting the stations in both DFs.
"""

### Creating a Geopandas dataframe of all TfL stations
df_all=pd.merge(df_plot,
                df1,
                on='NLC',
                how='right').drop(columns=['NETWORK', 'Zone'])
df_all["Coordinates"] = list(zip(df_all.EASTING, df_all.NORTHING))
df_all["Coordinates"] = df_all["Coordinates"].apply(Point)
gdf_all = gpd.GeoDataFrame(df_all, geometry="Coordinates")

# Creating a Geopandas dataframe of the bottom 30 stations by the 'Post-Covid impact' index
df_btm30=pd.merge(df_plot.tail(30),
                  df1,
                  on='NLC',
                  how='left')
df_btm30["Coordinates"] = list(zip(df_btm30.EASTING, df_btm30.NORTHING))
df_btm30["Coordinates"] = df_btm30["Coordinates"].apply(Point)
gdf_btm30 = gpd.GeoDataFrame(df_btm30, geometry="Coordinates")

# Creating a Geopandas dataframe of the top 30 stations by the 'Post-Covid impact' index
df_top30=pd.merge(df_plot.head(30),
                  df1,
                  on='NLC',
                  how='left').drop(columns=['NETWORK'])
df_top30["Coordinates"] = list(zip(df_top30.EASTING, df_top30.NORTHING))
df_top30["Coordinates"] = df_top30["Coordinates"].apply(Point)
gdf_top30 = gpd.GeoDataFrame(df_top30, geometry="Coordinates")

"""##### First, I created a simple geoplot using shapefiles"""

# A plot of the all TfL stations
fig, gax = plt.subplots(figsize=(18, 18))
ldn_df.plot(ax=gax, edgecolor="black", color="white")
gdf_downturn.plot(ax=gax, color='red', alpha = 0.5)
gdf_upturn.plot(ax=gax, color='blue', alpha = 0.5)

"""##### However, for an interactive and more informative map, I created this plot using Folium and json:"""

url = (
    "https://raw.githubusercontent.com/Osakwe1/vis/master/tubecreature/data"
)
tfl_network = f"{url}/tfl_lines.json"

map = folium.Map(location=[51.55, -0.25],
                 tiles="Stamen Terrain",
                 zoom_start=9.5)

for i,row in gdf_downturn.iterrows():
    #Setup the content of the popup

    iframe = folium.IFrame(f'{str(row["NAME"])} \n Zone: {str(row["Zone"])} \n Lines: {str(row["LINES"])} \n Downturn: {str(row["Downturn"])}',
                           width='100px',
                           height='150px')

    #Initialise the popup using the iframe
    popup = folium.Popup(iframe)

    #Add each row to the map
    folium.Marker(location=[row['y'],row['x']],
                  popup = popup, icon=folium.Icon(color='red', icon='')).add_to(map)

for i,row in gdf_upturn.iterrows():
    #Setup the content of the popup
    iframe = folium.IFrame(f'{str(row["NAME"])} Station \n Zone: {str(row["Zone"])} \n Lines: {str(row["LINES"])} \n Upturn: {str(row["Upturn"])}',
                          width='100px',
                          height='150px')

    #Initialise the popup using the iframe
    popup = folium.Popup(iframe)

    #Add each row to the map
    folium.Marker(location=[row['y'],row['x']],
                  popup = popup, icon=folium.Icon(color='blue', icon='')).add_to(map)

# # Create a legend using the tube_lines dictionary
# legend_html = """
# <div style="position: fixed;
#      bottom: 50px;
#      left: 50px;
#      width: 160px;
#      height: 480px;
#      border: 2px solid grey;
#      z-index:9999;
#      font-size:14px;
#      background-color:white;
#      ">
#      &nbsp; TfL Lines <br>
# """

# for line_name, line_info in tube_lines.items():
#     legend_html += f"""
#      &nbsp; <span style="color:{line_info['colour']};
#                   font-size: 20px;">&#9679;</span>
#                   {line_name} <br>
#     """

# legend_html += "</div>"

# map.get_root().html.add_child(folium.Element(legend_html))

folium.GeoJson(tfl_network, name="Tube map", style_function=style_function).add_to(map)
folium.GeoJson(ldn_df, name="London Boroughs map", zoom_on_click=False).add_to(map)

folium.LayerControl().add_to(map)

map

"""### Observations 🔎

Looking at the top 30 stations by *Downturn*, we spot a few trends:
- In East London, 9 of the stations of the East section of the District line from Plaistow to Upminister Bridge ranked in the top 30. In that region, near the East section of the Elizabeth line, 13 stations ranked among the 30 stations by Downturn.

- In West London, across the London Borough of Brent, 11 stations ranked in the top 30. An further 6 stations in close proximity to the area of Brent ranked in the top 30.

- Aside from those two clusters, the only other stations in the top 30 are Heathrow Terminal 5 EL and Battersea Park. Battersea Park is the least used station on the entire network by a large margin, but the recent opening of the Battersea Power station has likely caused a reduction in passenger use. Heathrow Terminal 5 EL's passenger downturn is seemingly unclear, especially as other stations at Heathrow generally saw significant upturn.

Looking at the top 30 stations by *Upturn*, we spot a few trends:
- On the West section of the Elizabeth line, 7 stations ranked in the top 30. These are stations on the newly opened Western section of the Elizabeth line.

- Within Central London, 19 stations ranked in the top 30. These are largely stations heavily frequented by tourists (Charing Cross, Oxford Circus, Leicester Square) or are gateway stations (King's Cross, Euston, Paddington).

If you're interested in looking even more detailed maps and data on the TfL network, you can check out [Tubecreature](https://tubecreature.com/) by University College London professor, Oliver O'Brien.

Thank you for your interest in this project! Check out what I'm working on next on [GitHub](https://github.com/Osakwe1)
"""